
```{r}
#install.packages("nflreadr")
```

```{r}
library(tidyverse)
library(shiny)
library(nflreadr)
library(modelr)

load("nflgames.RData")
load("postseasongames.RData")
load("nflteams.RData")
load("master_nflschedule.RData")
```

```{r}
#teams<- nflreadr::load_teams()|> select(team_abbr, team_name, team_conf, team_division)
#save(teams, file = "nflteams.RData")
#postseason_games <- nflreadr::load_schedules(1999:2025) 
```



```{r}
#updated_postseason<- postseason_games|>filter(game_type!="REG")
#save(updated_postseason, file = "postseasongames.RData")
```
```{r}
all_info_postseason<- updated_postseason|>
  mutate(margin = home_score - away_score)|>
  mutate(home_win = case_when(
    margin > 0 ~ 1,
    .default = 0 ))|>
  mutate(neutral = ifelse(game_type == "SB", TRUE, FALSE))
```
```{r}
old_teams <- data.frame(team_abbr = c("SD", "STL", "OAK"), team_name=c("San Diego Chargers", "Saint Louis Rams", "Oakland Raiders"), team_conf= c("AFC", "NFC", "AFC"), team_division = c("AFC West", "NFC West", "AFC West"))
final_teams<-rbind(teams, old_teams)
```


```{r}
rbind(nflgames, all_info_postseason)|>left_join(final_teams, by = c("home_team" = "team_abbr"))|>left_join(final_teams, by = c("away_team" = "team_abbr")) -> master_nflschedule

#master_nflschedule|>save(file = "master_nflschedule.RData")
```



```{r}
data<- master_nflschedule
ui<-fluidPage(title = "NFL Upset Predictor", 
              sidebarLayout(
                sidebarPanel(
                  selectInput("team", "NFL Team (Select a team for more options)", 
                              c("All", sort(unique(nflgames$home_team)))),
                  conditionalPanel(
                    "input.team != 'All'",
                    radioButtons("location", "Home vs. Away", c("Both", "Home", "Away")),
                    selectInput("rest_time", "Maxiumum Rest Time (Days)", c(21, 14, 7))
                  ),
                sliderInput("year", "Season", 1999, 2025, c(1999, 2025), sep = ""),
                selectInput("outdoors", "Indoors vs. Outdoors", c("Both", "Indoors", "Outdoors")),
                conditionalPanel(
                  "input.outdoors != 'Indoors'",
                  sliderInput("temp", "Temperature", -10, 110, c(-10,110)),
                  sliderInput("wind", "Wind Speed", 0, 75, c(0,75))
                ),
                radioButtons("rival", "Rivalry Games", c("Both", "Rivalries", "Non-Rivalries")),
                radioButtons("playoff", "Select:", c("Both", "Regular Season Games", "Postseason Games")),
              
              ),
              mainPanel(
                tabsetPanel(
                  tabPanel("Plots", 
                           plotOutput("h"), 
                           plotOutput("l")
                  ),
                  tabPanel("Upset Regression (Must Pick A Team)",
                           verbatimTextOutput("model"),
                           tableOutput("prob")
                  ),
                  tabPanel("Upset Calculator (Must Pick A Team)",
                           verbatimTextOutput("calculator_model"),
                           tableOutput("calculator_prob"),
                           plotOutput("calculator_histogram")
                           ),
                  tabPanel("About",
                           a("Visit Our GitHub Repository", 
                             href = "https://github.com/drlowe28/datasci306final", target ="_blank"))
                               
                             ))
              )
)


server<-function(input, output, session){
  filtered_data<-reactive({
    data<- master_nflschedule
    if (input$team != "All"){
      data <- master_nflschedule |> filter(home_team == input$team | away_team == input$team)
    }
    if(input$playoff == "Regular Season Games") {
      data <- data |> filter(game_type == "REG")
    } else if(input$playoff == "Postseason Games") {
      data <- data |> filter(game_type != "REG")
    }
    data <- data |> filter(between(season, input$year[1], input$year[2])) 
    if(input$outdoors == "Indoors") {
      data <- data |> filter((roof == "dome" | roof == "closed"))
    } else if(input$outdoors == "Outdoors") {
      data <- data |> filter(between(temp, input$temp[1], input$temp[2])) |>
                      filter(between(wind, input$wind[1], input$wind[2]))
    } else {
      data <- data |> filter(between(temp, input$temp[1], input$temp[2]) | 
               (roof == "dome" | roof == "closed")) |>
      filter(between(wind, input$wind[1], input$wind[2]) | 
              (roof == "dome" | roof == "closed"))
    }
    if (input$rival == "Rivalries") {
        data <- data |> filter(team_division.x == team_division.y)
    } else if (input$rival == "Non-Rivalries") {
        data <- data |> filter(team_division.x != team_division.y)
    }
    if(input$team != "All") {
      if (input$location == "Home") {
        data <- data |> filter(home_team == input$team)
      } else if (input$location == "Away") {
        data <- data |> filter(away_team == input$team)
      }
      
      if(input$rest_time == "7") {
        data <- data |> filter((home_team == input$team & home_rest <= 7) | 
                               (away_team == input$team & away_rest <= 7)) 
                               
      } else if (input$rest_time == "14") {
        data <- data |> filter((home_team == input$team & home_rest <= 14) | 
                               (away_team == input$team & away_rest <= 14))
      } else if (input$rest_time == "21") {
        data <- data |> filter((home_team == input$team & home_rest <= 21) | 
                               (away_team == input$team & away_rest <= 21))
      }
    }
    #print(nrow(data))
    data
    })
  output$h <- renderPlot({
    upsets<- filtered_data() |> 
      mutate(upset = ((spread_line >= 3.5 & margin < 0) | 
                        (spread_line <= -3.5 & margin > 0)))
    
    upsets|> ggplot(aes(x = spread_line, fill = upset)) + geom_histogram() +
      labs(title = "Upsets based on Spread Line over Selected Parameters",
           x = "Spread Line",
           caption = "(Positive spread means home team is favored)",
           y = "Count", fill = "Was the Selected Team Involved in an Upset?")+scale_fill_discrete(labels = c("FALSE" = "No", "TRUE" = "Yes"))+
      theme(plot.caption = element_text(size = 12))
  })
  output$l <- renderPlot({
    upsets<- filtered_data() |> 
      mutate(upset = ((spread_line >= 3.5 & margin < 0) | 
                        (spread_line <= -3.5 & margin > 0)))
    upsets |> group_by(season) |> summarize(upset_prop = mean(upset)) |>
      ggplot(aes(x = season, y = upset_prop)) + geom_line() + 
      geom_smooth(method = "lm") + 
      labs(title = "Upset Proportion over Selected Parameters",
           x = "Season",
           y = "Upset Proportion")
  })
  
  
  upsetModel<-reactive({
    modeldata <- master_nflschedule
    if (input$team != "All"){
      modeldata <- master_nflschedule |> filter(home_team == input$team | away_team == input$team)
    }
    modeldata <- modeldata |> mutate(upset = as.numeric(((spread_line >= 3.5 & margin < 0) | 
                                            (spread_line <= -3.5 & margin > 0))),
                                 outdoors = (roof != "dome" & roof != "closed"),
                                 home = (home_team == input$team), 
                                 playoff = (game_type != "REG"),
                                 rival = (team_division.x == team_division.y),
                                 rest_time = case_when(
                                   home_team == input$team ~ home_rest,
                                   away_team == input$team ~ away_rest,
                                   .default = NA
                                 ),
                                 temp_outdoor = ifelse(outdoors == 1, temp, 0),
                                  wind_outdoor = ifelse(outdoors == 1, wind, 0))
    modeldata
    
  })
  logmodel <- reactive ({
    glmModel <- glm(upset ~ outdoors + home + playoff + rival + rest_time + temp_outdoor + wind_outdoor,family = "binomial",data = upsetModel())
    glmModel
    })
  
  textModel <- reactive ({
    if(input$team == "All" | input$outdoors == "Both" | input$rival == "Both" | input$playoff == "Both" | 
       input$location == "Both") {
      "Must pick parameters other than \"Both\" for all of the parameters to receive a prediction."
    } else {
      tmodel <- data.frame(team = input$team, 
                           outdoors = ifelse(input$outdoors == "Outdoors", T, F), 
                           home = ifelse(input$location == "Home", T, F), 
                           playoff = ifelse(input$playoff != "Regular Season Games", T, F),
                           rival = ifelse(input$rival == "Rivalries", T, F),
                           rest_time = as.numeric(input$rest_time), 
                           temp_outdoor = ifelse(input$outdoors == "Outdoors", max(input$temp), 0),
                           wind_outdoor = ifelse(input$outdoors == "Outdoors", max(input$wind), 0))
      tmodel
    }
    
  })
  
  output$model <- renderPrint({
    if(input$team != "All") {
      summary(logmodel())
    } else {
      "PICK A TEAM"
    }
  })
  
  output$prob <- renderTable({
    if(input$team == "All" | input$outdoors == "Both" | input$rival == "Both" | input$playoff == "Both" | 
       input$location == "Both") {
      "Must pick parameters other than \"Both\" for all of the parameters to receive a prediction."
    }
    else{
    prob_output<-textModel() |> 
      add_predictions(logmodel()) |> 
        mutate(exppred = exp(pred)) |> 
      mutate(upsetprob = exppred / (1+exppred)) |>
        rename("Probability of Being Involved in an Upset" = upsetprob)
      prob_output|>select(ncol(prob_output))
      }
    })  
  
  
  
  
  calculator_table<-reactive({
    calculator_tab<-upsetModel()|>mutate(was_upset = as.numeric((home_team == input$team & margin < 0 & spread_line >= 3.5)|
                (away_team == input$team & margin > 0 & spread_line <= -3.5)))
    calculator_tab
  })
  
  
  calc_logmodel <- reactive ({
    calc_glmModel <- glm(was_upset ~ outdoors + home + playoff + rival + rest_time + temp_outdoor + wind_outdoor,family = "binomial",data = calculator_table())
    
    calc_glmModel
    })
  
  output$calculator_model<-renderPrint({
    if (input$team != "All"){
      summary(calc_logmodel())
      }
    else{
      "PICK A TEAM"
    }
      })
  
  output$calculator_prob<-renderTable({
    if(input$team == "All" | input$outdoors == "Both" | input$rival == "Both" | input$playoff == "Both" | 
       input$location == "Both") {
      "Must pick parameters other than \"Both\" for all of the parameters to receive a prediction."
    }
    else{
    calc_prob_output<-textModel() |> 
      add_predictions(calc_logmodel()) |> 
        mutate(exppred = exp(pred)) |> 
      mutate(upsetprob = exppred / (1+exppred)) |>
        rename("Probability of Being Upset by Another Team" = upsetprob)
      calc_prob_output|>select(ncol(calc_prob_output))
      }
    })
  
  output$calculator_histogram <- renderPlot({
    filtered_data()|>
      mutate(was_upset = (home_team == input$team & margin < 0 & spread_line >= 3.5)|
                (away_team == input$team & margin > 0 & spread_line <= -3.5))|>
      ggplot(aes(x = spread_line, fill = was_upset))+geom_histogram()+labs(
        x = "Spread Line", y = "Count", caption = "(Positive spread means home team is favored)", title = "Games Where Your Selected Team was Upset by Another Team (Must Pick a Team)", fill = "Was the selected team upset?") + scale_fill_discrete(labels = c("FALSE" = "No", "TRUE" = "Yes")) + theme(plot.caption = element_text(size = 12))
  })
      
}

shinyApp(ui, server)



```























```{r}
# negative spread is away team is favored

upsets<- nflgames|>arrange(spread_line)|>dplyr::select(home_team, away_team, home_score, away_score, margin, spread_line)|> filter((spread_line >= 6.5 & margin < 0) | (spread_line <= -6.5 & margin > 0))
upsets

#504 upsets total


all_nfl_games_betting<- nflgames|>filter(!is.na(margin) | is.na(spread_line))


head(all_nfl_games_betting)


#proportion of upsets
nrow(upsets)/nrow(all_nfl_games_betting)

```

```{r}
money_margin<- seq(14.5, -14.5, by = -0.5)

final_upset<-c()
for (i in money_margin){
  upsets_temp<- nflgames|>dplyr::select(home_team, away_team, home_score, away_score, margin, spread_line)|> filter((spread_line >= i & margin < 0) | (spread_line <= -i & margin > 0))
  prop_upset = nrow(upsets_temp)/nrow(all_nfl_games_betting)
  final_upset <- c(final_upset, prop_upset)
}
df<-data.frame(cutoff = money_margin, upset_prop = final_upset)

ggplot()+geom_line(aes(x = cutoff, y = upset_prop), data = df) +geom_vline(xintercept = 6.5, color = "red")

```
```{r}
#away teams being upset
upset_while_away<- upsets|>filter(margin>0)|>count(away_team)|>arrange(n)

upset_while_home<- upsets|>filter(margin<0)|>count(home_team)|>arrange(n)

left_join(upset_while_away, upset_while_home, by =c("away_team" ="home_team"))|>mutate(total_upsets = n.x+n.y)|>arrange(-total_upsets)


```
```{r}
desired_team <-"DET"
upsetModel <- master_nflschedule |> filter (home_team == desired_team | away_team == desired_team) |> 
  mutate(upset = as.numeric(((spread_line >= 3.5 & margin < 0) | 
                                            (spread_line <= -3.5 & margin > 0))),
                                 outdoors = (roof != "dome" & roof != "closed"),
                                 home = (home_team == desired_team),
                                 playoff = (game_type != "REG"),
                                 rival = (team_division.x == team_division.y),
                                 rest_time = case_when(
                                   home_team == desired_team ~ home_rest,
                                   away_team == desired_team ~ away_rest,
                                   .default = NA
                                 ),
                                  temp_outdoor = ifelse(outdoors == 1, temp, 0),  # replace NAs with 0
                                  wind_outdoor = ifelse(outdoors == 1, wind, 0))

#Then in your GLM:
glm(upset ~ outdoors + home + playoff + rival + rest_time + temp_outdoor + wind_outdoor,family = "binomial",data = upsetModel)|>summary()




```





